name: MyFirstWorkflow
on: 
  push:
    branches: 
    - main
  workflow_dispatch:
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "👋 Hello World!"
      
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: List files in repository
        run: |
          echo "The repository ActionInAction contains the following files:"
          tree
        
