name: My Second Training Workflow

on: 
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
        - run: echo "I am job_1 FIRST STEP"
        - run: echo "I am job_1 SECOND STEP"
  job_2:
     runs-on: ubuntu-latest
     steps:
       - run: echo "I am job_2 FIRST and ONLY STEP"
